---
title: "2_bootstrap"
author: "Dali_Nemecio"
date: "`r Sys.Date()`"
output: html_document
---

## Start ---------------------------------------------------------------------

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Set up

```{r}
#           Load Library **SPECIFY**------------------------------------------------------------
packages_needed<-c("tidyverse",
                   "tibble", 
                   "dplyr",
                   "rstudioapi") 

for (pkg in packages_needed){
if ( !require(pkg, character.only = TRUE)){
  library(pkg, character.only = TRUE)
} 
}

#           Collect Script Info and Change To Script Directory ---------------


#Script Directory
script_path_current <- getSourceEditorContext()$path
script_path_folder<-sub("/[^/]*$", "", script_path_current)
script_name<-sub(".*/", "", script_path_current)
script_name_base<-sub("\\..*$", "", script_name)

#Change directory in all code chunks to current script location
knitr::opts_knit$set(root.dir = script_path_folder)
 

#           Collect Run Info------------------------------------------- 
run_timestamp <- format(Sys.time(), "%Y_%m_%d_%H%M")

run_sessionInfo<-sessionInfo()

#           Shortcut Custom Functions --------------------------------------------------------


v <- function(data) {
  tab_name <- deparse(substitute(data))
  View(data, title = tab_name)
}

d<-function(data){
  dim(data)
}

l<-function(data){
  length(data)
}

u<-function(data){
  unique(data)
}

h<-function(data){
  head(data)
}

t<-function(data){
  tail(data)
}


```

### Load Data and Objects Required
```{r}
# Load Data - Collect .rda files ----------------------------------------

#       Find Previous Code Folder -----------------------------

# Find the last slash
last_slash <- max(gregexpr("/", script_path_folder)[[1]])

# Extract the substring
substring_after_last_slash <- substr(script_path_folder, last_slash + 1, nchar(script_path_folder))

# Extract the first number
first_number <- regmatches(substring_after_last_slash, regexpr("[0-9]+", substring_after_last_slash))

# Convert the first number to an integer and subtract 1
new_number <- as.integer(first_number) - 1

# Construct the new path
new_path <- paste0(
  substr(script_path_folder, 1, last_slash),
  new_number,
  "_*"
)

# Function to find directory matching the pattern
find_directory <- function(path_with_wildcard) {
  
  # Extract directory path without wildcard
  directory_path <- dirname(path_with_wildcard)
  
  # List files matching the pattern
  matching_files <- list.files(directory_path, pattern = basename(path_with_wildcard))
  
  # Check if any matching directory exists
  matching_directories <- matching_files[dir.exists(file.path(directory_path, matching_files))]
  
  if (length(matching_directories) > 0) {
    
    return(file.path(directory_path, matching_directories[1]))
    
  } else {
    return(NULL)
  }
}

# Find the actual directory matching the wildcard
rda_directory <- find_directory(new_path)

#       Load .rda files  ---------------------------------

# Get list of all .rda files recursively
rda_files <- list.files(path = rda_directory, 
                        pattern = "\\.rda$",
                        recursive = TRUE,
                        full.names = TRUE)

# Load each .rda file
for (file in rda_files) {
  load(file)
}

#       Collect starting Envr.  ---------------------------------

objects_starting<-ls()

 
```


### Check Input Object Sizes

```{r}

dim_check <- list()
has_mismatch <- FALSE  # Variable to track if there's a mismatch

for (obj_name in objects_starting) {
  if (obj_name %in% names(objects_dim_list)) {
    correct_dimensions <- objects_dim_list[[obj_name]]
    actual_object <- get(obj_name)
    actual_dimensions <- list(rows = nrow(actual_object), cols = ncol(actual_object))
    
    if (identical(correct_dimensions, actual_dimensions)) {
      dim_check[[obj_name]] <- "Dimensions match"
    } else {
      # Construct the mismatch message
      mismatch_msg <- "Dimensions mismatch:"
      if (correct_dimensions$rows != actual_dimensions$rows) {
        mismatch_msg <- paste(mismatch_msg, "Expected rows is", correct_dimensions$rows,
                              "actual is", actual_dimensions$rows)
      }
      if (correct_dimensions$cols != actual_dimensions$cols) {
        mismatch_msg <- paste(mismatch_msg, "Expected columns is", correct_dimensions$cols,
                              "actual is", actual_dimensions$cols)
      }
      # Store the mismatch message in dim_check
      dim_check[[obj_name]] <- mismatch_msg
      has_mismatch <- TRUE  # Set has_mismatch to TRUE if there's a mismatch
    }
  }
}

# Print the output
print(dim_check)

# Check if there's a mismatch and stop if true
if (has_mismatch) {
  stop("There is at least one object with mismatched dimensions.")
}  else {"No mismatch in loaded object sizes, continue code execution." }

```

# MAIN ------------------------------

# Set seed
```{r}
set.seed(2026)
```
### **mod** Sequester participants for test bootstrap 
```{r}

# Select PT IDs for Testing and Training -----------

test_ptIDs<-sample_n(df_hp1_rna_dat_select_tran, 5) %>%rownames(.)
train_ptIDs<-setdiff(rownames(df_hp1_rna_dat_select_tran), test_ptIDs )



# RNA DATA -----------------------------------
 
# Training Pts (15)
rna_train_pts<-subset( df_hp1_rna_dat_select_tran, rownames(df_hp1_rna_dat_select_tran) %in% train_ptIDs)
rna_train_pts <- rna_train_pts[train_ptIDs, ]

# Testing PTs (5)
rna_test_pts<-subset( df_hp1_rna_dat_select_tran, rownames(df_hp1_rna_dat_select_tran) %in% test_ptIDs)
rna_test_pts <- rna_test_pts[test_ptIDs, ]


# MBio DATA -----------------------------------
 
# Training Pts (15)
mbio_train_pts<-subset( df_mbiocomp_dat_pres_pop_trans, rownames(df_mbiocomp_dat_pres_pop_trans) %in% train_ptIDs)
mbio_train_pts <- mbio_train_pts[train_ptIDs, ]

# Testing PTs (5)
mbio_test_pts<-subset( df_mbiocomp_dat_pres_pop_trans, rownames(df_mbiocomp_dat_pres_pop_trans) %in% test_ptIDs)
mbio_test_pts <- mbio_test_pts[test_ptIDs, ]


```




### Bootstrap For Loop Fxn

```{r}


bootstrapfxn<-function(RNA_enter, MBIO_enter, numbpts){ 
  
  
      
      #       Define Input Data --------------------------------------------------------------
      
                          input1_RNA<-RNA_enter
                          input2_mbiocomp<-MBIO_enter
      
                          
                          
                          
      # Blank For Collecting 10 runs of Bootstrap Iterations of 100 --------------------
                          
                          boot10_Master_analysis<-list()
                          boot10_pt_ID_per_iteration<-list()
                          
      # STARTING OUTERLOOP -------------------------------------
      
      for(j in 1:10){ 
        
      #       Blanks Inner For Loop Building and Counting -----------------------------------
      
      print(paste0("Enter outerloop: ", j))
        
                          #blank for microbe vs gene correlation building
                          
                          iteration_blank_RNA<-c(rep(NA, length(nrow(input1_RNA))))
      
                          microbes_vs_genes_loop_building<-input1_RNA%>%
                                                          mutate(iteration = iteration_blank_RNA,                                                                     .before=(colnames(input1_RNA[1])))%>%
                                                          .[FALSE,]
                          
                          
                          #blank for TV- microbe/gene corr 
                         
                          iteration_blank_tvmic<-c(rep(NA, nrow(df_lincs_gene_tv_sharedgenes)))
                          
                          TV_microbe_loop_building<-df_lincs_gene_tv_sharedgenes%>%
                                                    mutate(iteration = iteration_blank_tvmic,                                                                      .before=(colnames(df_lincs_gene_tv_sharedgenes[1])))%>%
                                                    .[FALSE,]
                          
                          #blank for collecting PT ID and Loop Iteration
                          
                          pt_ID_per_iteration<- data.frame(iteration= as.numeric(),
                                                              pt_ID= as.character()
                                                            )
                          
                          
             
      #       Begin Inner For Loop ----------------------------------------------------------
      1
      set.seed(2026)
                          
      for ( i in 1:200){  
                         print(paste0("Enter iteration : ",i)) 
      #Select 10 patients 
                          loop_pt_ID<-rownames(input1_RNA[sample(nrow(input1_RNA), numbpts),])
                          
      #Reccord 10 patients 
                          
                          iteration_current<-rep(i, length(loop_pt_ID))
                          
                          
                          pt_ID_per_iteration_loop<-data.frame(iteration = iteration_current, 
                                                               pt_ID = loop_pt_ID)
                          
                          pt_ID_per_iteration<-rbind(pt_ID_per_iteration, pt_ID_per_iteration_loop)
                          
      #pull microbe and gene data from 10 patients
                          
                          
                            input1_loop_RNA<-input1_RNA%>%
                                              filter(row.names(input1_RNA) %in% loop_pt_ID)
                            
      
                            input2_loop_mbiocomp<-input2_mbiocomp%>%
                                                  filter(row.names(input2_mbiocomp) %in% loop_pt_ID)
      
                          ##View(microbes_vs_genes_corr_loop)
                          
      #Spearman Correlation - looping 
      
                            microbes_vs_genes_corr_loop<-cor(input2_loop_mbiocomp, 
                                                             input1_loop_RNA, 
                                                             method = "spearman")
                            microbes_vs_genes_corr_loop<-as.data.frame(microbes_vs_genes_corr_loop)
                            
      
                            
                            
                            #iteration reccord
                            
                            iteration_count_current_mvg<- c(rep( i ,nrow(microbes_vs_genes_corr_loop)))
                            
                            microbes_vs_genes_corr_loop_iter<-microbes_vs_genes_corr_loop%>%
                                                      mutate(iteration =iteration_count_current_mvg, 
                                                             .before = colnames(microbes_vs_genes_corr_loop[1]))
                            
                           
                            #add to building sheet
                            microbes_vs_genes_loop_building<-rbind(microbes_vs_genes_loop_building, microbes_vs_genes_corr_loop_iter )
      
                          
        #transpose and calc tv corr 
       
                           microbes_vs_genes_corr_loop_trans<-as.data.frame(base::t(microbes_vs_genes_corr_loop))
                           
                           
                            TV_microbe_gene_corr_loop<-cor(microbes_vs_genes_corr_loop_trans,                                                                         y = df_lincs_gene_tv_sharedgenes, method = "spearman")
                             
                            TV_microbe_gene_corr_loop<-as.data.frame(TV_microbe_gene_corr_loop)
       
                            iteration_count_current_tv<- c(rep(i,nrow(TV_microbe_gene_corr_loop) ))
                            
                            TV_microbe_gene_corr_loop_iter<-TV_microbe_gene_corr_loop%>%
                                                                mutate(iteration = iteration_count_current_tv,                                                               .before = colnames(.[1]))
      
      
                            TV_microbe_loop_building<-rbind(TV_microbe_loop_building,TV_microbe_gene_corr_loop_iter)

                            
                            print(paste0("Exit iteration : ",i)) 
      
      }
                          
                          
      #       Post Inner For Loop Data Processing -----------------------------------------------
                          
                          #rename the building data to closing data 
                          TV_microbe_loop_closing<-TV_microbe_loop_building%>%
                            rename(., TV_Mic_iteration = iteration)
                          
                            
                            microbes_vs_genes_loop_closing<- microbes_vs_genes_loop_building%>%
                                                            rename(., MvG_iteration = iteration )
                            
                            #merge TV microbe and microbe vs genes dataframes
                            Master_analysis<-cbind(TV_microbe_loop_closing, microbes_vs_genes_loop_closing)
      
                                                  #prepare blank vector for addition of TV state 
                            tv_state_blank = c(rep(NA, nrow(Master_analysis)))
                            
      
                            #rearrange and insert blank column
                             Master_analysis<-Master_analysis%>%
                                              mutate(TV_state = (tv_state_blank), 
                                                     .before = colnames(Master_analysis[1]))
                          
                            #generate microbe name column
                            Master_analysis$Microbes<-rownames(Master_analysis)
                            rownames(Master_analysis)<-NULL
                            
                            #rearrange
                            penultimate_index<-(ncol(Master_analysis)-1)
                            
                            Master_analysis<-Master_analysis%>%
                                               select(Microbes, TV_state, TV_Mic_iteration, tenofovir, MvG_iteration, 5:penultimate_index)
                            
                            #remove trailing digits in microbe name
                            Master_analysis<-Master_analysis%>%
                                              mutate(Microbes = str_remove(Microbes, "\\d+$"))
                            
      
                            #insert microbe TV_states 
                            Master_analysis <- within(Master_analysis, TV_state[Microbes == "Gardnerella vaginalis" |
                                                                                Microbes == "Mobiluncus mulieris"  ] <- 1 )
                            
                            Master_analysis<- within(Master_analysis, TV_state[Microbes == "Lactobacillus iners" |
                                                                                Microbes == "Lactobacillus crispatus" ]<- -1 ) 
      
       
            
                            
      
      
      # Collect 10 runs of bootstrap -----------------
      
      ### Master_analysis 
                            
      if(length(boot10_Master_analysis)==0){
        
        boot10_Master_analysis[[1]]<-Master_analysis
        
      } else {
        
        boot10_Master_analysis[[(length(boot10_Master_analysis)+1)]]<-Master_analysis
        
      }
      
      ### PT ID per iteration
      
      if(length(boot10_pt_ID_per_iteration)==0){
        
        boot10_pt_ID_per_iteration[[1]]<-pt_ID_per_iteration
        
      } else {
        
        boot10_pt_ID_per_iteration[[(length(boot10_pt_ID_per_iteration)+1)]]<-pt_ID_per_iteration
        
      }
                            
      
      print(paste0("Exit outerloop: ", j))
      
      # CLOSING OUTERLOOP ------------
      }
                          
                          
      return(list(boot10_pt_ID_per_iteration = boot10_pt_ID_per_iteration, 
                  boot10_Master_analysis = boot10_Master_analysis))
      

        
  
  
  } # END bootstrapfxn
                    
```

### *mod* Execute Bootstrap fxn
```{r}

# Train
train_out<-bootstrapfxn(rna_train_pts, mbio_train_pts, 10)


# test 
test_out<-bootstrapfxn(rna_test_pts, mbio_test_pts, 3)

# extract results 
train_boot10_pt_ID_per_iteration<-train_out$boot10_pt_ID_per_iteration
train_boot10_Master_analysis<-train_out$boot10_Master_analysis

test_boot10_pt_ID_per_iteration<-test_out$boot10_pt_ID_per_iteration
test_boot10_Master_analysis<-test_out$boot10_Master_analysis


```

### Save Object Sizes ***Specify Objects***
```{r}


objects_created <- c("train_boot10_pt_ID_per_iteration",       
                     "train_boot10_Master_analysis",   
                     "test_boot10_pt_ID_per_iteration",        
                     "test_boot10_Master_analysis"   
                                                        
                     )

reccord_dim <- function(objects) {
  
  result <- list()
  
  for (obj_name in objects) {
    
    if (exists(obj_name)) {
      
      obj <- get(obj_name)
      
      if (is.data.frame(obj) || is.matrix(obj)) {
        
        rows <- nrow(obj)
        cols <- ncol(obj)
        result[[obj_name]] <- list(rows = rows, cols = cols)
        
      } else {
        
        warning(paste("Object labeled ", obj_name, "is not a data frame or a matrix. Skipping."))
      }
      
    } else {
      
      warning(paste("Object", obj_name, "does not exist. Skipping."))
      
    }
  }
  return(result)
}

objects_dim_list<-reccord_dim(objects_created)




print("CREATED OBJECT DIMENSIONS AS FOLLOWS :")
print(objects_dim_list)
      

```


### Exporting and Clean Up - Part 1/2
```{r}
#           Create Output File ------------------------------------------------------


current_output_folder<-paste0(script_name_base, "_", run_timestamp, ".Rmd")

dir.create(current_output_folder)

script_path_with_output_folder <- file.path(script_path_folder, 
                                            current_output_folder)

setwd(script_path_with_output_folder) # need to restate for each code chunk

#           Export Executed Code ----------------------------------------------------

copy_and_output_code <- function(script_path) {
  if (file.exists(script_path)) {
    
    rstudioapi::documentSave()
    
    script_content <- readLines(script_path)
    
    writeLines(script_content, current_output_folder)
  } else {
    message("Error: The specified script path does not exist.")
  }
}

# Call the function to copy and export the code
copy_and_output_code(script_path_current)

#           Export Run Info ---------------------------------------------------------

writeLines(capture.output(run_sessionInfo), "sessionInfo.txt")

```


### Exporting and Clean Up - Part 2/2 **Specify Objects**
```{r}

setwd(script_path_with_output_folder) # need to restate for each code chunk

#           Export Objects as .rda - **SPECIFY OBJECTS**----------------------------------------------------

objects_save<-c( objects_created, "objects_dim_list")

                            
save(list=objects_save,                   
     file = "env_obj.rda")


 
```


### Clear Env./Re-Add Generated Objects
```{r}
setwd(script_path_with_output_folder) # need to restate for each code chunk

#           Clear Environment/Re-Add Generated Objects  ------------------------------------------------------


#clear environment
rm(list = ls()) #USE VERY CAREFULLY ONLY ACTIVATE AT END OF PIPELINE
# rm(list = objects_save)

#readd the objects
load("env_obj.rda")


```


