---
title: "0_import_data.Rmd"
author: "Dali_Nemecio"
date: "`r Sys.Date()`"
output: 
  html_document:
    highlight: zenburn
---
# Set up 
## Shortcuts 
```{r}
source("/Users/dalinemecio/Documents/1_Rotations/Brubaker/R/x_smaller_folders/short_cuts/short_cuts.R")
```

## Library and Filepath 

```{r setup, include=FALSE}

# 1. rmd set up----------------------------------

    knitr::opts_chunk$set(echo = TRUE)
    

# 2. Load Library **SPECIFY**--------------------

    packages_needed<-c("readr",
                       "rstudioapi", "data.table") 
    
    
    for (pkg in packages_needed){
    if ( !require(pkg, character.only = TRUE)){
      library(pkg, character.only = TRUE)
    } 
         
    }



# 3. Collect Script Info and Change To Script Directory ---------------

    #Script Directory
    script_path_current <- getSourceEditorContext()$path
    script_path_folder<-sub("/[^/]*$", "", script_path_current)
    script_name<-sub(".*/", "", script_path_current)
    script_name_base<-sub("\\..*$", "", script_name)
    
    #Change directory in all code chunks to current script location
    knitr::opts_knit$set(root.dir = script_path_folder) 
     
# 4. Collect Run Info------------------------------------------- 

    run_timestamp <- format(Sys.time(), "%Y_%m_%d_%H%M")
    
    run_sessionInfo<-sessionInfo()
    
    objects_starting<-ls()


# 5. Custom functions --------------------------------------------------------

    suppress_lines <- function(expr, lines = Inf) {
      capture <- capture.output(expr)
      if (length(capture) > lines) {
        cat(capture[1:lines], "\n", "Truncated output. Total lines:", length(capture), "\n")
      } else {
        cat(capture, "\n")
      }
    }


```

## Define Retrieval Paths
```{r}

path_ibd<-"/Users/dalinemecio/Documents/1_Rotations/Brubaker/7_Raw_Files_Library/2025_08_21_IBDMDB_Alex_Realligned/"

path_lincs<-"/Users/dalinemecio/Documents/1_Rotations/Brubaker/7_Raw_Files_Library/data_LINCS/"

```

### Load Data and Objects Required
```{r}
# Load Data - Collect .rda files ----------------------------------------

#       Find Previous Code Folder -----------------------------

# Find the last slash
last_slash <- max(gregexpr("/", script_path_folder)[[1]])

# Extract the substring
substring_after_last_slash <- substr(script_path_folder, last_slash + 1, nchar(script_path_folder))

# Extract the first number
first_number <- regmatches(substring_after_last_slash, regexpr("[0-9]+", substring_after_last_slash))

# Convert the first number to an integer and subtract 1
new_number <- as.integer(first_number) - 1

# Construct the new path
new_path <- paste0(
  substr(script_path_folder, 1, last_slash),
  new_number,
  "_*"
)

# Function to find directory matching the pattern
find_directory <- function(path_with_wildcard) {
  
  # Extract directory path without wildcard
  directory_path <- dirname(path_with_wildcard)
  
  # List files matching the pattern
  matching_files <- list.files(directory_path, pattern = basename(path_with_wildcard))
  
  # Check if any matching directory exists
  matching_directories <- matching_files[dir.exists(file.path(directory_path, matching_files))]
  
  if (length(matching_directories) > 0) {
    
    return(file.path(directory_path, matching_directories[1]))
    
  } else {
    return(NULL)
  }
}

# Find the actual directory matching the wildcard
rda_directory <- find_directory(new_path)

#       Load .rda files  ---------------------------------

objects_beforeload<-ls()

# Get list of all .rda files recursively
rda_files <- list.files(path = rda_directory, 
                        pattern = "\\.rda$",
                        recursive = TRUE,
                        full.names = TRUE)

# Load each .rda file
for (file in rda_files) {
  load(file)
}


#       Collect starting Envr.  ---------------------------------

objects_starting<-ls()

 
```


## Upload From Data Library
```{r}

# IBDMDB -  ---------------------------------------------------------

    mbio_taxo <- read.csv(paste0(path_ibd, "ibdmdb_16S_IBD_data_species.csv")) 
    PT_meta <- read.csv(paste0(path_ibd,"hmp2_metadata_2018-08-20.csv"))
    trans_data <- fread(paste0(path_ibd,"ibdmdb_host_tx_counts.tsv"), header = TRUE)

# LINCS Data sets ---------------------------------------------------


    lincs_mean_alldrugs<-fread(paste0(path_lincs, "cp_mean_coeff_mat.tsv"), header = TRUE) 
     

```



### Confirm Data Upload 

```{r}
# Confirm Data Upload -----------------------------------------------------

objects_current<-ls()

objects_uploaded <- c(
  "drugFC_ordered",         
  "ordered_bact_76_final",  
  "ordered_drugs_176_final", 
  "mbio_taxo",              
  "PT_meta",                
  "trans_data",            
  "lincs_mean_alldrugs"     
)


for (z in objects_uploaded) {
  obj <- get(z)  
  print(paste0("STRUCTURE of ", z, " :"))
  print(paste(paste(
    suppress_lines(paste("\n", str(obj), sep = ""), lines = 5),  
    collapse = " x ")
  ))
  
  rm(obj, z)
}



```

### Save Object Sizes 
```{r}

objects_created <- objects_uploaded

reccord_dim <- function(objects) {
  
  result <- list()
  
  for (obj_name in objects) {
    
    if (exists(obj_name)) {
      
      obj <- get(obj_name)
      
      if (is.data.frame(obj) || is.matrix(obj)) {
        
        rows <- nrow(obj)
        cols <- ncol(obj)
        result[[obj_name]] <- list(rows = rows, cols = cols)
        
      } else if(is.vector(obj)){
        
        length <- length(obj)
      
        result[[obj_name]] <- list(rows = length, cols = 0)
      
      } else {
        
        warning(paste("Object labeled ", obj_name, "is not a data frame or a matrix, or a vector. Skipping."))
      }
      
    } else {
      
      warning(paste("Object", obj_name, "does not exist. Skipping."))
      
    }
  }
  return(result)
}

object_dim_list<-reccord_dim(objects_created)

```


### Exporting and Clean Up
```{r}
#           Create Output File ------------------------------------------------------


current_output_folder<-paste0(script_name_base, "_", run_timestamp, ".Rmd")

dir.create(current_output_folder)

script_path_with_output_folder <- file.path(script_path_folder, 
                                            current_output_folder)

setwd(script_path_with_output_folder) # need to restate for each code chunk

#           Export Executed Code ----------------------------------------------------

copy_and_output_code <- function(script_path) {
  if (file.exists(script_path)) {
    
    rstudioapi::documentSave()
    
    script_content <- readLines(script_path)
    
    writeLines(script_content, current_output_folder)
  } else {
    message("Error: The specified script path does not exist.")
  }
}

# Call the function to copy and export the code
copy_and_output_code(script_path_current)

#           Export Run Info ---------------------------------------------------------

writeLines(capture.output(run_sessionInfo), "sessionInfo.txt")

```


### Exporting and Clean up - **Specify Objects**
```{r}

setwd(script_path_with_output_folder) # need to restate for each code chunk

#           Export Objects as .rda - **SPECIFY OBJECTS**----------------------------------------------------


objects_save<-c(objects_uploaded, "object_dim_list")

                            
save(list=objects_save,                   
     file = "env_obj.rda")


 
```


### Clear Env./Re-Add Generated Objects

```{r}
setwd(script_path_with_output_folder) # need to restate for each code chunk

#           Clear Environment/Re-Add Generated Objects  ------------------------------------------------------


#clear environment
rm(list = ls()) #USE VERY CAREFULLY ONLY ACTIVATE AT END OF PIPELINE
# rm(list = objects_save)

#readd the objects
load("env_obj.rda")


  ## END ---------------------------------------------------------------------


```














# End ---------------------------------------------------------------------

