---
title: "0_import_data.Rmd"
author: "Dali_Nemecio"
date: "`r Sys.Date()`"
output: 
  html_document:
    highlight: zenburn
---

### Set Up 

```{r setup, include=FALSE}
# Set Up - Section 1  -------------------------------------------------------
#           rmd set up----------------------------------------
knitr::opts_chunk$set(echo = TRUE)


#           Load Library **SPECIFY**------------------------------------------------------------

packages_needed<-c("readr",
                   "rstudioapi") 


for (pkg in packages_needed){
if ( !require(pkg, character.only = TRUE)){
  library(pkg, character.only = TRUE)
} 
     
}



#           Collect Script Info and Change To Script Directory ---------------


#Script Directory
script_path_current <- getSourceEditorContext()$path
script_path_folder<-sub("/[^/]*$", "", script_path_current)
script_name<-sub(".*/", "", script_path_current)
script_name_base<-sub("\\..*$", "", script_name)
#Change directory in all code chunks to current script location

knitr::opts_knit$set(root.dir = script_path_folder) 
 

```

```{r}
# Set Up - Section 2 -------------------------------------------------------

#           Collect Run Info------------------------------------------- 

run_timestamp <- format(Sys.time(), "%Y_%m_%d_%H%M")

run_sessionInfo<-sessionInfo()


objects_starting<-ls()


#           Custom functions --------------------------------------------------------



suppress_lines <- function(expr, lines = Inf) {
  capture <- capture.output(expr)
  if (length(capture) > lines) {
    cat(capture[1:lines], "\n", "Truncated output. Total lines:", length(capture), "\n")
  } else {
    cat(capture, "\n")
  }
}


# End Set up

```



### Upload Data
```{r}
# Upload Mehp1 Data -------------------------------------------------------


#PrEP Dat - RNA 

df_hp1_rna_dat<-read.delim("/Users/dalinemecio/Documents/1_Rotations/Brubaker/Raw_Files_Library/data_PrEP_mehp1/mehp1_rna_data.txt", header = TRUE, sep =",")

df_hp1_rna_ph<-read.delim("/Users/dalinemecio/Documents/1_Rotations/Brubaker/Raw_Files_Library/data_PrEP_mehp1/mehp1_rna_phenotypes.txt", header = TRUE, sep ="\t")

#PrEP Dat - Microbiome Composition
df_hp1_mbiocomp_dat<-read.delim("/Users/dalinemecio/Documents/1_Rotations/Brubaker/Raw_Files_Library/data_PrEP_mehp1/mehp1_mbiomeComp_data.txt", header = TRUE, sep = ",")

df_hp1_mbiocomp_ph<-read.delim("/Users/dalinemecio/Documents/1_Rotations/Brubaker/Raw_Files_Library/data_PrEP_mehp1/mehp1_mbiomeComp_phenotypes.txt", header = TRUE, sep = ",")



# Upload LINCS Datasets ---------------------------------------------------

#LINCS Data

df_lincs_cp_mean_tv<-read_tsv("/Users/dalinemecio/Documents/1_Rotations/Brubaker/Raw_Files_Library/data_LINCS/cp_mean_coeff_tenofovir.tsv")

df_lincs_gene_tv<-read_csv("/Users/dalinemecio/Documents/1_Rotations/Brubaker/Raw_Files_Library/data_LINCS/LINCS_tenofovir_matrix.csv")  


```



### Confirm Data Upload -----------------------------------------------------

```{r}
# Confirm Data Upload -----------------------------------------------------

objects_current<-ls()

objects_uploaded <- objects_current[grep("^df", objects_current)]

for (z in objects_uploaded) {
  obj <- get(z)  # Get the actual object
  print(paste0("STRUCTURE of ", z, " :"))
  print(paste(paste(
    suppress_lines(paste("\n", str(obj), sep = ""), lines = 5),  # Insert newline before each line
    collapse = " x ")
  ))
  
  rm(obj, z)
}



```

### Save Object Sizes 
```{r}
objects_uploaded

reccord_dim <- function(objects) {
  
  result <- list()
  
  for (obj_name in objects) {
    
    if (exists(obj_name)) {
      
      obj <- get(obj_name)
      
      if (is.data.frame(obj) || is.matrix(obj)) {
        
        rows <- nrow(obj)
        cols <- ncol(obj)
        result[[obj_name]] <- list(rows = rows, cols = cols)
        
      } else {
        
        warning(paste("Object", obj_name, "is not a data frame or a matrix. Skipping."))
      }
      
    } else {
      
      warning(paste("Object", obj_name, "does not exist. Skipping."))
      
    }
  }
  return(result)
}

object_dim_list<-reccord_dim(objects_uploaded)



```


### Exporting and Clean Up
```{r}
#           Create Output File ------------------------------------------------------


current_output_folder<-paste0(script_name_base, "_", run_timestamp, ".Rmd")

dir.create(current_output_folder)

script_path_with_output_folder <- file.path(script_path_folder, 
                                            current_output_folder)

setwd(script_path_with_output_folder) # need to restate for each code chunk

#           Export Executed Code ----------------------------------------------------

copy_and_output_code <- function(script_path) {
  if (file.exists(script_path)) {
    
    rstudioapi::documentSave()
    
    script_content <- readLines(script_path)
    
    writeLines(script_content, current_output_folder)
  } else {
    message("Error: The specified script path does not exist.")
  }
}

# Call the function to copy and export the code
copy_and_output_code(script_path_current)

#           Export Run Info ---------------------------------------------------------

writeLines(capture.output(run_sessionInfo), "sessionInfo.txt")

```


### Exporting and Clean up - **Specify Objects**
```{r}

setwd(script_path_with_output_folder) # need to restate for each code chunk

#           Export Objects as .rda - **SPECIFY OBJECTS**----------------------------------------------------


objects_save<-c(objects_uploaded, "object_dim_list")

                            
save(list=objects_save,                   
     file = "env_obj.rda")


 
```


### Clear Env./Re-Add Generated Objects

```{r}
setwd(script_path_with_output_folder) # need to restate for each code chunk

#           Clear Environment/Re-Add Generated Objects  ------------------------------------------------------


#clear environment
rm(list = ls()) #USE VERY CAREFULLY ONLY ACTIVATE AT END OF PIPELINE
# rm(list = objects_save)

#readd the objects
load("env_obj.rda")


  ## END ---------------------------------------------------------------------


```



